### ISSUE TITLE
Crash Report - 8/11/24, Game crash upon startup of  "The Intruders". Log Included

### ISSUE THREAD

**Issue by Lexinyxia** [TeamOct/fictional-octo-system#34]
### Platforms

Windows

### Game Build

Release build 146

### Mod Build / Version

1.1 beta-build 2.2

### Issue

Game crash via java.lang.Nullpointerexception upon mission startup. Mission is "The Intruders"

### Steps to reproduce

Quite literally just playing through the campaign. It crashed the instant i tried to open The Intruders, and does so every single time i do so. I did not do anything to the game's files and even re-installed the mod today just to be sure.

### Mods used

FOS and FOS OST only.

### Save file

The Intruders.
[sector-fos-lumoni-44.zip](https://github.com/user-attachments/files/16785027/sector-fos-lumoni-44.zip)

### (Crash) logs

Mindustry has crashed. How unfortunate.
Version: release build 146
OS: Windows 10 x64 (amd64)
Java Version: 1.8.0_411
Runtime Available Memory: 3616mb
Cores: 4
Mods: fos:1.1 beta build-2.2, fosost:1.0.3

java.lang.NullPointerException
	at fosost.FOSOSTMod.lambda$new$2(FOSOSTMod.java:72)
	at arc.Events.fire(Events.java:53)
	at arc.Events.fire(Events.java:43)
	at mindustry.core.World.endMapLoad(World.java:232)
	at mindustry.core.World.loadGenerator(World.java:253)
	at mindustry.core.World.loadSector(World.java:264)
	at mindustry.core.World.loadSector(World.java:257)
	at mindustry.core.Control.playNewSector(Control.java:515)
	at mindustry.core.Control.lambda$playSector$33(Control.java:508)
	at mindustry.core.UI.lambda$loadAnd$10(UI.java:268)
	at arc.util.Timer$1.run(Timer.java:88)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:194)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

### Submission

- [X] I have updated to the latest release (https://github.com/TeamOct/FOS/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am sure that the bug is not caused by other mods I have installed, or, in rare cases, the game itself.

**Comment by Lexinyxia** [comment]
I am certain the crash is not caused by Mindustry as the crash is consistent and doesn't seem to happen at any other time with any other mod.

_I would like to ALSO note that the game very much does think I launched to the sector, as every time it happens I have to wait for the resources to launch again._

**Comment by Lexinyxia** [comment]
Nevermind.
Issue was a one-time event caused by Mindustry. I guess it just happens every time Mindustry is restarted after a long time of not being launched. Closing this issue as resolved, no assistance needed.

**Comment by nekit508** [comment]
(._.(
